"""pizza_type_sauces

Revision ID: 122e0b558456
Revises: 5bcb52aaecde
Create Date: 2024-06-25 18:32:27.780692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122e0b558456'
down_revision = '5bcb52aaecde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_type_sauce',
    sa.Column('pizza_type_id', sa.Uuid(), nullable=False),
    sa.Column('sauce_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_type_id'], ['pizza_type.id'], ),
    sa.ForeignKeyConstraint(['sauce_id'], ['sauce.id'], ),
    sa.PrimaryKeyConstraint('pizza_type_id', 'sauce_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza_type_sauce')
    # ### end Alembic commands ###
