"""longer_description

Revision ID: 2911cc7f651d
Revises: 40ae859bce90
Create Date: 2024-06-15 19:11:32.204650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2911cc7f651d'
down_revision = '40ae859bce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizza_type', 'description',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizza_type', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
