"""fix_sauces

Revision ID: cc6efbb5d105
Revises: 122e0b558456
Create Date: 2024-06-25 18:44:16.207661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6efbb5d105'
down_revision = '122e0b558456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pizza_type_sauce_pizza_type_id_fkey', 'pizza_type_sauce', type_='foreignkey')
    op.create_foreign_key(None, 'pizza_type_sauce', 'pizza_type', ['pizza_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizza_type_sauce', type_='foreignkey')
    op.create_foreign_key('pizza_type_sauce_pizza_type_id_fkey', 'pizza_type_sauce', 'pizza_type', ['pizza_type_id'],['id'])
    # ### end Alembic commands ###
